using Microsoft.AspNetCore.Mvc;
using ProvaPub.Services.Interfaces;

namespace ProvaPub.Controllers
{
	/// <summary>
	/// Ao rodar o código abaixo o serviço deveria sempre retornar um número diferente, mas ele fica retornando sempre o mesmo número.
	/// 1 - Faça as alterações para que o retorno seja sempre diferente
	/// 2 - Tome cuidado 
	/// </summary>
	[ApiController]
	[Route("[controller]")]
	public class Parte1Controller :  ControllerBase
	{
		private readonly IRandomService _randomService;

		public Parte1Controller(IRandomService randomService)
		{
			_randomService = randomService;
		}
		
		
		/// <summary>
		/// Retrieves a random integer value from the random service.
		/// </summary>
		/// <remarks>
		/// This endpoint is designed to provide a different random number with each request.
		/// Ensure that the random service is implemented correctly to avoid repeated results.
		/// </remarks>
		/// <returns>
		/// An integer value generated by the random service.
		/// </returns>
		/// <response code="200">Returns a random integer.</response>
		/// <response code="500">If there is an issue with the random service or server.</response>
		[HttpGet]
		public async Task<int> Index()
		{
			return await _randomService.GetRandom();
		}
	}
}
